### ISSUE TITLE
Broadcom WiFi issues

### ISSUE THREAD

**Issue by fobos531** [Sniki/Lenovo-Thinkpad-T440S#1]
I dont know why, but my post triggered the modfilter somehow and completely bugged out on the forums so im writing here.

Regarding the wifi issue

-------

Anyways, here are the files you requested: http://mega.nz/file/1PJRmYDY#MSJRtzA14VjKN7zSDy7AFOjN0nqunRk1UNFzXtAMW1E

I also included the complete EFI which is causing me problems so you can check whether I messed up anything in config.plist :p

The files suffixed with _Catalina denotes that I'm using AirportBrcmFixUp from your Catalina EFI (works perfectly fine) and the ones _BigSur are from your most recent EFI (problematic).

Additionally, I can manually turn on the adapter through SysPrefs -> Network, but no networks are found. I cannot connect to them by manually specifying SSID & passphrase.

**Comment by Sniki** [comment]
Checked the files and i will fix it for everyone.

I will load all necessary kexts.
Now we can specify 'maxkernel' and 'minkernel' so each kext can load only on the macOS version it is specified to.

Thanks for the Ioreg.
Will add the device entry into 'config.plist > Add > DeviceProperties > ' as well.

**Comment by Sniki** [comment]
Solved in master with https://github.com/Sniki/Lenovo-Thinkpad-T440S/commit/8f015bab6a67bcb821540f19102d260237854db1

Try latest EFI from source and report back with results in forum.

Open Network of System Preferences.
Delete all networks, as shown in "Erase All Networks".
Delete the Library \ Preferences \ SystemConfiguration \ NetworkInterfaces.plist file.
Restart.

Thanks !
