### ISSUE TITLE
Can you have a solution for garbled screen when CSM disabled?

### ISSUE THREAD

**Issue by MaximeH38** [Sniki/Lenovo-Thinkpad-T440S#11]
Hello,
Sorry for that, i don’t know if you can help me but my ASUS laptop get a garbled screen. I have follow your instructions but without success..
Thank you! :)
(my english is bad, i’m french oops)

**Comment by Sniki** [comment]
Hi, this is Off topic, i have written the way how to patch the edid for garbled screen but unfortunately i have no time for other laptops and stuff, so i don't know about your ASUS laptop, you should research and see if someone did make a guide already and maybe provided the solution.
