### ISSUE TITLE
Apple Logo, then Reboot

### ISSUE THREAD

**Issue by philsrfn** [Sniki/Lenovo-Thinkpad-T440S#12]
Hey Sniki!
When I put the EFI folder on the USB drive, right besides to the com.apple.recover.boot folder, and try to boot from it, after altering the config.plist, it just gives me an apple Logo, and after half a minute it reboots. How do I fix this?

**Comment by philsrfn** [comment]
When I installed with your EFI half a year ago, it worked just fine...

**Comment by philsrfn** [comment]
Yeah, I still kinda have that problem

**Comment by philsrfn** [comment]
...

**Comment by Sniki** [comment]
Guide works fine as of readme, however beyond that i haven't updated and don't know what happened, i plan a near future update so if there is something i notice, it will be fixed.
