### ISSUE TITLE
update auf Monterey

### ISSUE THREAD

**Issue by loewenjunges** [Sniki/Lenovo-Thinkpad-T440S#13]
Danke, es funktioniert bis Big Sur super

Bei einem update oder einer Neuinstallation von BigSur auf Monterey bekomme ich nach einem Neustart immer folgende Meldung

![Alt-Text](https://i.imgur.com/zW5ZdW5.png)

bzw. kommt die Meldung das das ein Firmwareupdate nicht gefunden wurde

Haben Sie eine Idee wie ich das Problem weg bekomme

ich habe schon ein wenig gebastelt, leider kommt immer die Fehlermeldung

**Comment by Sniki** [comment]
Unfortunately, Monterey dropped support for the MacBookPro11,1 or better say Haswell series so there is no official support for it.
There may be tweaking and workarounds and a possibility to run it however i have no intention to update and change stuff to work on Monterey for now or maybe not in the future.
This repository will get an update to latest OpenCore version and additional fixes and enhancements however i have no plan to unofficially add support to unsupported stuff.
