### ISSUE TITLE
Installer issue

### ISSUE THREAD

**Issue by IBN-5100-tan** [Sniki/Lenovo-Thinkpad-T440S#14]
I get to the installer and it starts installing and says it will take 2 hours and 20 mins and then starts to increase and is now at 18 hours.  I let it go through once and didn't touch it and it failed.  How long should the install of Big Sur take? Am I doing something wrong or does it just take that long?

**Comment by philsrfn** [comment]
Hello, can you please tell me what did you do to get to the installer? Every step please, as I am not getting any further than the apple logo.

**Comment by IBN-5100-tan** [comment]
I followed this tutorial: https://www.youtube.com/watch?v=j-Cm30I_DEw&t=1s&ab_channel=BrandonYen 

You have to follow all of the steps of a regular hackintosh install (which I wasn't doing), and then you can use the files from this repo. You just need the EFI files from here.

**Comment by philsrfn** [comment]
Hey, sorry to bother, but did you get it working? For me it doesn't. It shows the apple logo and then reboots...

**Comment by IBN-5100-tan** [comment]
Did you see my previous comment? And if so, did you follow the entire tutorial for doing a hackintosh?
