### ISSUE TITLE
En0 not showing up as built-in

### ISSUE THREAD

**Issue by igorkulman** [Sniki/Lenovo-Thinkpad-T440S#2]
According to all the iMessage guides the `en0` adapter should be recognized as built-in, it is not in this EFI according to Hackintool.

**Comment by Sniki** [comment]
It is because the SSDT-IGBE.aml disables the Lan in ACPI level to fix instant wake.

IntelMausi.kext however does ignore it and load it but sleep works well afterwards.

Im aware of the issue and will update the SSDT-IGBE with the correct LAN device with proper sleep state.

**Comment by igorkulman** [comment]
Do you think it is safe to try to activate iMessage on a clean install with a hack like this which makes it show up as built-in

![Screenshot 2020-11-26 at 10 25 21](https://user-images.githubusercontent.com/4746070/100332499-c08bf480-2fd1-11eb-8eca-ac0b7bc8652a.png)

**Comment by Sniki** [comment]
Don’t risk any ID(s) blacklisting.

Will fix it tonight, it may work fine but the ACPI device is missing anyway so it is required.

**Comment by Sniki** [comment]
Solved in master with https://github.com/Sniki/Lenovo-Thinkpad-T440S/commit/699e901a242bdef68ee48f322dd245d9882a680e

Make sure to reset Network Interfaces after you update SSDT-IGBE.aml with the new one.
- Open Network of System Preferences.
- Delete all networks, as shown in "Erase All Networks".
- Delete the Library \ Preferences \ SystemConfiguration \ NetworkInterfaces.plist file.
- Restart.
