### ISSUE TITLE
Complete Audio Patching

### ISSUE THREAD

**Issue by Sniki** [Sniki/Lenovo-Thinkpad-T440S#4]
@fewtarius sorry for bothering you there but i noticed across forums that you seem to know a lot about audio codecs.

I have this ALC3232 (ALC292) Audio Codec on my Haswell generation Lenovo ThinkPad(s) that no matter how much and how many times i tried i cannot fix the static noise on headphones without using ALCPlugFix.
For some reasons `01A70724` does fix the issue but does not work on cold boot, adding it into the `configdata` doesn't seem to work on AppleALC, however a sleep and then wake, it works, so `wakeconfigdata` is working correctly on it.

Second issue is the docking station that these laptops do have.
The docking station does have a combo jack as well and it works fine but having two external inputs as LineIn in this codec case, after i plug the headphones in the laptop jack, the LineIn will have no Audio Input but the docking station one will work, or vice versa.
So having the possibility to set the laptop jack input as External Mic instead of LineIn maybe would help but maybe that is not the problem either.

If you have any other place to discuss this, let me know.

I will redo the info.plist , layout**.plist/xml and platforms**.plist/xml files so you can take a look at if you can.

CodecDump(s) are in the Docs/Audio folder of this repo.

**Comment by ghost** [comment]
Howdy!  Have you run through my jack sense gist yet? https://gist.github.com/fewtarius/0ee689cf725c27c43af0aea83b04b882

**Comment by Sniki** [comment]
> Howdy! Have you run through my jack sense gist yet? https://gist.github.com/fewtarius/0ee689cf725c27c43af0aea83b04b882

Didn't know about it but i just checked it and i have those values set correctly.

I had lost my resources of patched version with docking station support, almost done and will provide these soon.

Question: how do i know which instruction i need for jack sense, in my case i send 24 (01a70724).
The problem in my case is on boot, reboot, a wake from sleep fixes the problem. so WakeConfigData is working fine.
[HDAConfigDefault.zip](https://github.com/Sniki/Lenovo-Thinkpad-T440S/files/5611038/HDAConfigDefault.zip)
I attached the HDAConfigDefault as i am doing the Platforms right now.

**Comment by ghost** [comment]
Does sending 70725 change anything for you?  I don't see anything that stands out.

**Comment by Sniki** [comment]
> Does sending 70725 change anything for you? I don't see anything that stands out.

Unfortunately not, however one stupid thing is if i close the lid for a second and reopen the static noise goes away and audio works through headphones.
Maybe AppleALC sends the sleep signal fast (as soon as lid closes) for sleep preparation and the lid open trigger wakeconfigdata so 01A70724 initiates which fixes the static noise.

What about External Microphone instead of LineIn, have you had success with that ?

Any hints on how can i configure it ?

[Resources.zip](https://github.com/Sniki/Lenovo-Thinkpad-T440S/files/5611407/Resources.zip)
