### ISSUE TITLE
Unable to Upgrade from Catalina to Big Sur

### ISSUE THREAD

**Issue by ZhirenXu** [Sniki/Lenovo-Thinkpad-T440S#6]
When upgrade in System Preference:
         The progress bar went about halfway then prompt to restart. The machine would attempt to restart but actually did a log out. After log in previous progress couldn't been resumed and system upgrade would start from beginning.
         Fix attempt: hit restart button in login page. Not effective, no matter it's a countdown restart or sudo reboot the machine will always do a log out.

When upgrade from recovery image:
         Follow OpenCore's vanilla guide, using macrecovery.py to download Big Sur recovery image and boot from USB. Choose to boot from Mac(External) but stuck at Apple logo, no progress bar. When enable verbose mode it shows in-memory panic.

My kernel panic screenshot:
![kernel-panic-1](https://user-images.githubusercontent.com/55563667/112071927-2be07000-8b47-11eb-8b8c-2d0f9435f6b8.jpg)
![kernel-panic-2](https://user-images.githubusercontent.com/55563667/112071932-2e42ca00-8b47-11eb-9710-7e88ce83a97a.jpg)

My kext folder:
![image](https://user-images.githubusercontent.com/55563667/112072317-f25c3480-8b47-11eb-92d0-f74184efd032.png)

My Config.plist:
https://drive.google.com/file/d/1ZrdKh_gN1ueANZBV5h0gRUP9BSd4dV_o/view?usp=sharing

Appreciate if you could take a look.
I also want to say a big thank-you for getting all kexts ready which makes my hackintosh experience much better.

**Comment by Sniki** [comment]
Please use tmx86 forum for troubleshooting on the guide thread. double-check your work as i just tested on mine and reached installer just fine.
