### ISSUE TITLE
macOS Mojave10.14.6 use ALCPlugFix can not work

### ISSUE THREAD

**Issue by fsnhljz** [Sniki/Lenovo-Thinkpad-T440S#8]
ALCPlugFix在macOS Mojave10.14.6 下不起作用 3.5mm earphone port

**Comment by adminstig** [comment]
Hmm... working for me without problem

**Comment by fsnhljz** [comment]
> Hmm... working for me without problem

i mean 3.5mm earphone port
can you?

**Comment by adminstig** [comment]
> > Hmm... working for me without problem
> 
> i mean 3.5mm earphone port
> can you?

Sorry, my mistake ((
Indeed, it doesn't work in Mojave. Only noise and that's all.

**Comment by fsnhljz** [comment]
> > > Hmm... working for me without problem
> > 
> > 
> > i mean 3.5mm earphone port
> > can you?
> 
> Sorry, my mistake ((
> Indeed, it doesn't work in Mojave. Only noise and that's all.

Thank you. If it really doesn't work, just give it up. Forget it

**Comment by adminstig** [comment]
Big Sur working good. I just checked.
Interesting to check on Catalina.

**Comment by Sniki** [comment]
duplicated of #9 and as mentioned there, will be fixed in a near future update.
