### ISSUE TITLE
ALC3232 in Big Sur

### ISSUE THREAD

**Issue by DeniZka** [Sniki/Lenovo-Thinkpad-T440S#9]
Need some changes in com.black-dragon74.ALCPlugFix.plist
**remove:** 
```

   <key>ServiceIPC</key>
    <false/>

```
this key is depricated

**Comment by itsecstig** [comment]
Only BS? For Mojave not work?

**Comment by DeniZka** [comment]
I don't know about older versions. It's my first setup. 
System can't read **com.black-dragon74.ALCPlugFix.plist** due to **ServiceIPC** key is present. 
So **ALCPluginFix** won't start.
If you cant find **ALCPlugnFix** in CPU process just try... You can edit installed file in **/Library/LaunchAgents**

**Comment by itsecstig** [comment]
Ok. Thanx! I'll try.
Спасибо! ))

**Comment by Sniki** [comment]
Planned for a general update in the near future and to be fixed as well.
